/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientRouteImport } from './routes/client'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as ClientProfileRouteImport } from './routes/client.profile'
import { Route as ClientPacksRouteImport } from './routes/client.packs'
import { Route as ClientNotificationsRouteImport } from './routes/client.notifications'
import { Route as ClientBookingsRouteImport } from './routes/client.bookings'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPacksRoute = ClientPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => ClientRoute,
} as any)
const ClientNotificationsRoute = ClientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBookingsRoute = ClientBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ClientRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/packs': typeof PacksRoute
  '/planning': typeof PlanningRoute
  '/promotions': typeof PromotionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/packs': typeof ClientPacksRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/packs': typeof PacksRoute
  '/planning': typeof PlanningRoute
  '/promotions': typeof PromotionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/packs': typeof ClientPacksRoute
  '/client/profile': typeof ClientProfileRoute
  '/client': typeof ClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/packs': typeof PacksRoute
  '/planning': typeof PlanningRoute
  '/promotions': typeof PromotionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/packs': typeof ClientPacksRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/auth'
    | '/blog'
    | '/booking'
    | '/client'
    | '/contact'
    | '/packs'
    | '/planning'
    | '/promotions'
    | '/blog/$slug'
    | '/client/bookings'
    | '/client/notifications'
    | '/client/packs'
    | '/client/profile'
    | '/client/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/auth'
    | '/blog'
    | '/booking'
    | '/contact'
    | '/packs'
    | '/planning'
    | '/promotions'
    | '/blog/$slug'
    | '/client/bookings'
    | '/client/notifications'
    | '/client/packs'
    | '/client/profile'
    | '/client'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/auth'
    | '/blog'
    | '/booking'
    | '/client'
    | '/contact'
    | '/packs'
    | '/planning'
    | '/promotions'
    | '/blog/$slug'
    | '/client/bookings'
    | '/client/notifications'
    | '/client/packs'
    | '/client/profile'
    | '/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookingRoute: typeof BookingRoute
  ClientRoute: typeof ClientRouteWithChildren
  ContactRoute: typeof ContactRoute
  PacksRoute: typeof PacksRoute
  PlanningRoute: typeof PlanningRoute
  PromotionsRoute: typeof PromotionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/packs': {
      id: '/client/packs'
      path: '/packs'
      fullPath: '/client/packs'
      preLoaderRoute: typeof ClientPacksRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/notifications': {
      id: '/client/notifications'
      path: '/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof ClientNotificationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/bookings': {
      id: '/client/bookings'
      path: '/bookings'
      fullPath: '/client/bookings'
      preLoaderRoute: typeof ClientBookingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ClientRouteChildren {
  ClientBookingsRoute: typeof ClientBookingsRoute
  ClientNotificationsRoute: typeof ClientNotificationsRoute
  ClientPacksRoute: typeof ClientPacksRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientBookingsRoute: ClientBookingsRoute,
  ClientNotificationsRoute: ClientNotificationsRoute,
  ClientPacksRoute: ClientPacksRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  BookingRoute: BookingRoute,
  ClientRoute: ClientRouteWithChildren,
  ContactRoute: ContactRoute,
  PacksRoute: PacksRoute,
  PlanningRoute: PlanningRoute,
  PromotionsRoute: PromotionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
