/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientRouteImport } from './routes/client'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ClientProfileRouteImport } from './routes/client.profile'
import { Route as ClientPacksRouteImport } from './routes/client.packs'
import { Route as ClientNotificationsRouteImport } from './routes/client.notifications'
import { Route as ClientBookingsRouteImport } from './routes/client.bookings'
import { Route as CatalogIdRouteImport } from './routes/catalog.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminPlanningRouteImport } from './routes/admin.planning'
import { Route as AdminPacksRouteImport } from './routes/admin.packs'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminKnowledgeRouteImport } from './routes/admin.knowledge'
import { Route as AdminCreativeStudioRouteImport } from './routes/admin.creative-studio'
import { Route as AdminCoachesRouteImport } from './routes/admin.coaches'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminAiAgentRouteImport } from './routes/admin.ai-agent'
import { Route as AdminActivitiesRouteImport } from './routes/admin.activities'

const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPacksRoute = ClientPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => ClientRoute,
} as any)
const ClientNotificationsRoute = ClientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBookingsRoute = ClientBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ClientRoute,
} as any)
const CatalogIdRoute = CatalogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CatalogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanningRoute = AdminPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacksRoute = AdminPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreativeStudioRoute = AdminCreativeStudioRouteImport.update({
  id: '/creative-studio',
  path: '/creative-studio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachesRoute = AdminCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiAgentRoute = AdminAiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/packs': typeof PacksRoute
  '/planning': typeof PlanningRoute
  '/promotions': typeof PromotionsRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/ai-agent': typeof AdminAiAgentRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/admin/creative-studio': typeof AdminCreativeStudioRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/packs': typeof AdminPacksRoute
  '/admin/planning': typeof AdminPlanningRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/packs': typeof ClientPacksRoute
  '/client/profile': typeof ClientProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/contact': typeof ContactRoute
  '/packs': typeof PacksRoute
  '/planning': typeof PlanningRoute
  '/promotions': typeof PromotionsRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/ai-agent': typeof AdminAiAgentRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/admin/creative-studio': typeof AdminCreativeStudioRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/packs': typeof AdminPacksRoute
  '/admin/planning': typeof AdminPlanningRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/packs': typeof ClientPacksRoute
  '/client/profile': typeof ClientProfileRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/packs': typeof PacksRoute
  '/planning': typeof PlanningRoute
  '/promotions': typeof PromotionsRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/ai-agent': typeof AdminAiAgentRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/admin/creative-studio': typeof AdminCreativeStudioRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/packs': typeof AdminPacksRoute
  '/admin/planning': typeof AdminPlanningRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/packs': typeof ClientPacksRoute
  '/client/profile': typeof ClientProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/booking'
    | '/catalog'
    | '/client'
    | '/contact'
    | '/packs'
    | '/planning'
    | '/promotions'
    | '/admin/activities'
    | '/admin/ai-agent'
    | '/admin/articles'
    | '/admin/bookings'
    | '/admin/clients'
    | '/admin/coaches'
    | '/admin/creative-studio'
    | '/admin/knowledge'
    | '/admin/messages'
    | '/admin/packs'
    | '/admin/planning'
    | '/admin/promotions'
    | '/admin/settings'
    | '/admin/users'
    | '/blog/$slug'
    | '/catalog/$id'
    | '/client/bookings'
    | '/client/notifications'
    | '/client/packs'
    | '/client/profile'
    | '/admin/'
    | '/client/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/auth'
    | '/blog'
    | '/booking'
    | '/catalog'
    | '/contact'
    | '/packs'
    | '/planning'
    | '/promotions'
    | '/admin/activities'
    | '/admin/ai-agent'
    | '/admin/articles'
    | '/admin/bookings'
    | '/admin/clients'
    | '/admin/coaches'
    | '/admin/creative-studio'
    | '/admin/knowledge'
    | '/admin/messages'
    | '/admin/packs'
    | '/admin/planning'
    | '/admin/promotions'
    | '/admin/settings'
    | '/admin/users'
    | '/blog/$slug'
    | '/catalog/$id'
    | '/client/bookings'
    | '/client/notifications'
    | '/client/packs'
    | '/client/profile'
    | '/admin'
    | '/client'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/booking'
    | '/catalog'
    | '/client'
    | '/contact'
    | '/packs'
    | '/planning'
    | '/promotions'
    | '/admin/activities'
    | '/admin/ai-agent'
    | '/admin/articles'
    | '/admin/bookings'
    | '/admin/clients'
    | '/admin/coaches'
    | '/admin/creative-studio'
    | '/admin/knowledge'
    | '/admin/messages'
    | '/admin/packs'
    | '/admin/planning'
    | '/admin/promotions'
    | '/admin/settings'
    | '/admin/users'
    | '/blog/$slug'
    | '/catalog/$id'
    | '/client/bookings'
    | '/client/notifications'
    | '/client/packs'
    | '/client/profile'
    | '/admin/'
    | '/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookingRoute: typeof BookingRoute
  CatalogRoute: typeof CatalogRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  ContactRoute: typeof ContactRoute
  PacksRoute: typeof PacksRoute
  PlanningRoute: typeof PlanningRoute
  PromotionsRoute: typeof PromotionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/packs': {
      id: '/client/packs'
      path: '/packs'
      fullPath: '/client/packs'
      preLoaderRoute: typeof ClientPacksRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/notifications': {
      id: '/client/notifications'
      path: '/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof ClientNotificationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/bookings': {
      id: '/client/bookings'
      path: '/bookings'
      fullPath: '/client/bookings'
      preLoaderRoute: typeof ClientBookingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/catalog/$id': {
      id: '/catalog/$id'
      path: '/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof CatalogIdRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planning': {
      id: '/admin/planning'
      path: '/planning'
      fullPath: '/admin/planning'
      preLoaderRoute: typeof AdminPlanningRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packs': {
      id: '/admin/packs'
      path: '/packs'
      fullPath: '/admin/packs'
      preLoaderRoute: typeof AdminPacksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creative-studio': {
      id: '/admin/creative-studio'
      path: '/creative-studio'
      fullPath: '/admin/creative-studio'
      preLoaderRoute: typeof AdminCreativeStudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coaches': {
      id: '/admin/coaches'
      path: '/coaches'
      fullPath: '/admin/coaches'
      preLoaderRoute: typeof AdminCoachesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-agent': {
      id: '/admin/ai-agent'
      path: '/ai-agent'
      fullPath: '/admin/ai-agent'
      preLoaderRoute: typeof AdminAiAgentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminAiAgentRoute: typeof AdminAiAgentRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCoachesRoute: typeof AdminCoachesRoute
  AdminCreativeStudioRoute: typeof AdminCreativeStudioRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPacksRoute: typeof AdminPacksRoute
  AdminPlanningRoute: typeof AdminPlanningRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminAiAgentRoute: AdminAiAgentRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminCoachesRoute: AdminCoachesRoute,
  AdminCreativeStudioRoute: AdminCreativeStudioRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPacksRoute: AdminPacksRoute,
  AdminPlanningRoute: AdminPlanningRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CatalogRouteChildren {
  CatalogIdRoute: typeof CatalogIdRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogIdRoute: CatalogIdRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

interface ClientRouteChildren {
  ClientBookingsRoute: typeof ClientBookingsRoute
  ClientNotificationsRoute: typeof ClientNotificationsRoute
  ClientPacksRoute: typeof ClientPacksRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientBookingsRoute: ClientBookingsRoute,
  ClientNotificationsRoute: ClientNotificationsRoute,
  ClientPacksRoute: ClientPacksRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  BookingRoute: BookingRoute,
  CatalogRoute: CatalogRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  ContactRoute: ContactRoute,
  PacksRoute: PacksRoute,
  PlanningRoute: PlanningRoute,
  PromotionsRoute: PromotionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
